import type { Clip } from "@/lib/types";

export const mockClips: Clip[] = [
  {
    id: "clip_001",
    niche: "Creator tools",
    title: "I built a landing page in 20 minutes",
    handle: "@productmuse",
    durationSeconds: 28,
    views: 1824300,
    likes: 142300,
  },
  {
    id: "clip_002",
    niche: "Creator tools",
    title: "3 hooks that stop the scroll",
    handle: "@hooklab",
    durationSeconds: 19,
    views: 942300,
    likes: 82300,
  },
  {
    id: "clip_003",
    niche: "Fitness",
    title: "5-min desk stretch routine",
    handle: "@coach.rina",
    durationSeconds: 24,
    views: 2311200,
    likes: 212900,
  },
  {
    id: "clip_004",
    niche: "Fitness",
    title: "The simplest fat-loss checklist",
    handle: "@lift.with.myles",
    durationSeconds: 31,
    views: 1532000,
    likes: 118500,
  },
  {
    id: "clip_005",
    niche: "Food",
    title: "One-pan spicy noodles",
    handle: "@weeknightwok",
    durationSeconds: 26,
    views: 3215400,
    likes: 304100,
  },
  {
    id: "clip_006",
    niche: "Food",
    title: "The crunchiest air-fryer potatoes",
    handle: "@crispyclub",
    durationSeconds: 22,
    views: 874000,
    likes: 67900,
  },
  {
    id: "clip_007",
    niche: "AI",
    title: "This prompt makes your content better",
    handle: "@promptcoach",
    durationSeconds: 29,
    views: 1967400,
    likes: 164800,
  },
  {
    id: "clip_008",
    niche: "AI",
    title: "Automate your weekly newsletter",
    handle: "@ops.ai",
    durationSeconds: 27,
    views: 1129800,
    likes: 90500,
  },
  {
    id: "clip_009",
    niche: "Beauty",
    title: "Glass-skin routine for beginners",
    handle: "@skinbylea",
    durationSeconds: 30,
    views: 2452100,
    likes: 287300,
  },
  {
    id: "clip_010",
    niche: "Beauty",
    title: "The only lip combo I wear now",
    handle: "@makeup.anna",
    durationSeconds: 17,
    views: 1367700,
    likes: 152400,
  },
  {
    id: "clip_011",
    niche: "Travel",
    title: "Hidden cafes in Tokyo (save this)",
    handle: "@daytrip.dae",
    durationSeconds: 32,
    views: 2045600,
    likes: 215900,
  },
  {
    id: "clip_012",
    niche: "Travel",
    title: "How to pack a week in a carry-on",
    handle: "@carryononly",
    durationSeconds: 23,
    views: 997600,
    likes: 78300,
  },
];

export const niches = Array.from(new Set(mockClips.map((c) => c.niche)));

